name: gaudioso_app
description: "A new Flutter project."

publish_to: 'none'

version: 2.0.0+0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  intl: ^0.20.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  flutter_localizations: 
    sdk: flutter
  mask_text_input_formatter: ^2.9.0
  google_fonts: ^6.3.2
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.2.3
  lucide_icons_flutter: ^3.1.5
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  image_picker: ^1.0.8
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
